### ISSUE TITLE
Request to add "intensity" field to the PointCloud2 message 

### ISSUE THREAD

**Issue by ghost** [RobotecAI/RGLGazeboPlugin#15]
### Feature request

The plugin only supplied the _x,y and z_ fields to the message. Refer [this line](https://github.com/RobotecAI/RGLGazeboPlugin/blob/399540496b9ab4fea384846ae57cefc10c6116c6/RGLServerPlugin/src/Lidar.cc#L184). 

The resulting message fields look like this:
```
fields:
- name: x
  offset: 0
  datatype: 7
  count: 1
- name: y
  offset: 4
  datatype: 7
  count: 1
- name: z
  offset: 8
  datatype: 7
  count: 1
```

But for reference, the Gazebo GPU Lidar supplies the following fields,

```
fields:
- name: x
  offset: 0
  datatype: 7
  count: 1
- name: y
  offset: 4
  datatype: 7
  count: 1
- name: z
  offset: 8
  datatype: 7
  count: 1
- name: intensity
  offset: 16
  datatype: 7
  count: 1
- name: ring
  offset: 24
  datatype: 4
  count: 1
```

The ring field might not be that necessary, but the intensity field is. And it does look like the field might be available in the [API core.h](https://github.com/RobotecAI/RobotecGPULidar/blob/9786a9689ee0c84208753b98ee35f2c7ddb67d24/include/rgl/api/core.h#L205).

I understand this might make filling the message data a little more complicated and inefficient, since this will mean doing a strided copy of the intensity field into the data array, which is not as elegant as using [memcpy here](https://github.com/RobotecAI/RGLGazeboPlugin/blob/399540496b9ab4fea384846ae57cefc10c6116c6/RGLServerPlugin/src/Lidar.cc#L190), but the intensity field is an important features that many projects rely on. 

I will be looking at verifying that the intensity field is in fact calculated and reliable in the API. 

Please let me know your thoughts.
